name: Bump_Dependencies

on:
  schedule:
    - cron: "5 8 * * Sun" #  8:05 every Sunday

jobs:
  Bump_Dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Setup PNPM
        uses: pnpm/action-setup@master
        with:
          version: latest

      - name: setup npm-check-updates
        run: pnpm install -g npm-check-updates

      - run: |
          ncu -u --dep prod
          pnpm install

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "fix: update Dependencies"
          title: "fix: update Dependencies"
          labels: Dependencies
          branch: "Bump_Dependencies"

  Bump_devDependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Setup PNPM
        uses: pnpm/action-setup@master
        with:
          version: latest

      - name: setup npm-check-updates
        run: pnpm install -g npm-check-updates

      - run: |
          ncu -u --dep dev
          pnpm install

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "chore: update devDependencies"
          title: "chore: update devDependencies"
          labels: Dependencies
          branch: "Bump_devDependencies"
